### ISSUE TITLE
Clerk-Remix-CloudflareWorkers

### ISSUE THREAD

**Issue by aerojeyenth** [clerkinc/remix-auth-starter#13]
Clerk's USP according to me its support for Edge environments. But I always face some issue when trying to get it set up. Could you please kindly provide a starter project and add it to getting started tutorial on your site for Remix + Cloudflare Worker + Clerk ?

**Comment by LekoArts** [comment]
Hi!

Please reach out to our support or go to https://feedback.clerk.com for feature requests. Thanks!
