### ISSUE TITLE
Getting 401s for a short period of time even though a user is logged in

### ISSUE THREAD

**Issue by DarrenBaldwin07** [clerkinc/remix-auth-starter#14]
This might not be the correct place to put this issue so happy to move it if needed. 

Ever since I started using Clerk + Remix, I have consistently gotten 401 errors almost every time on a cold login. The typical flow is that I get a 401, it hangs for 1.5 seconds (with a white screen), and then finally shows the user the app. Keep in mind that I am using Remix's V2_errorBoundary and have also implemented everything exactly how it was described in this doc: https://clerk.com/docs/quickstarts/remix (it even mentions **"If you are seeing a 401 after a short period of time, even though your user is logged in, please verify you have implemented this section"**).

**Comment by franklinjavier** [comment]
![image](https://github.com/clerkinc/remix-auth-starter/assets/440220/59e45943-9882-43f7-ba21-24c27a781393)

**Comment by AdiRishi** [comment]
Ran into this myself, made an issue to track it in the main clerk js repository - https://github.com/clerk/javascript/issues/2166

**Comment by LekoArts** [comment]
Please see https://github.com/clerk/javascript/issues/2166#issuecomment-1827960060
