### ISSUE TITLE
Clerk + Remix is broken

### ISSUE THREAD

**Issue by marcus-sa** [clerkinc/remix-auth-starter#4]
I'm having the same issues locally.
![Screenshot from 2022-05-07 20-20-22](https://user-images.githubusercontent.com/8391194/167266919-9b7bbfa3-92ed-44cb-8c15-8cf4cac8f7de.png)

**Comment by MarcoMruz** [comment]
I have similar problem when switched in Remix app from React 17 to 18

**Comment by abenhamdine** [comment]
No problem here with react 17 : 

my deps :  

```
    "@clerk/remix": "^0.5.11",
    "@remix-run/express": "^1.6.5",
    "@remix-run/node": "^1.6.5",
    "@remix-run/react": "^1.6.5",
    "compression": "^1.7.4",
    "cross-env": "^7.0.3",
    "express": "^4.18.1",
    "morgan": "^1.10.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
"devDependencies": {
    "@remix-run/dev": "^1.6.5",
    "@remix-run/eslint-config": "^1.6.5",
    "@types/react": "^17.0.45",
    "@types/react-dom": "^17.0.17",
    "autoprefixer": "^10.4.7",
    "concurrently": "^7.3.0",
    "eslint": "^8.15.0",
    "nodemon": "^2.0.16",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.4.14",
    "tailwindcss": "^3.1.6",
    "typescript": "^4.7.4"
  },
```

**Comment by marmorse** [comment]
Confirmed issues with 18.  Anyone have any luck getting Clerk working with React 18?

**Comment by jalexanderII** [comment]
Any progress here? Or Clark, should I need another Auth provider if I am using React 18?  If I take this repo, close it, upgrade all of the dependencies, and run it for the `ssr-demo` and `ssr-user demo,` I get `Error: AuthContext not found.`

**Comment by nikosdouvlis** [comment]
Hello everyone. Apologies for keeping this open for so long, but all React18-related issues were solved ~8 months ago so I'll be closing this stale issue now. Thanks :)

**Comment by zackfencedev** [comment]
Issues persist in remix latest.
